version: '3'

volumes:
    mysql-data:

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql

    app:
        image: elielsonbatista/env-php
        container_name: app
        ports:
            - "80:8000"
        depends_on:
            - mysql
        volumes:
            - .:/app
        command: php -S 0.0.0.0:8000 -t public
